# Generated by Django 5.2 on 2025-05-13 03:15

import django.core.validators
import django.db.models.deletion
import django_resized.forms
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='default.png', force_format='JPEG', keep_meta=True, null=True, quality=90, scale=0.5, size=[200, 200], upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, default='default.png', force_format='JPEG', keep_meta=True, null=True, quality=90, scale=0.5, size=[1920, 1080], upload_to='images/rooms/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'jfif', 'PNG', 'JPG'])])),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_.\\)\\(\\[\\]\\\\\\|\\s]{4,}$', message="Allowed characters: a-z, A-Z, 0-9, '_', '.', '', '(', ')', '[', ']' and ' '.")])),
                ('description', models.TextField(validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_.\\)\\(\\[\\]\\\\\\|\\s]{4,}$', message="Allowed characters: a-z, A-Z, 0-9, '_', '.', '', '(', ')', '[', ']' and ' '.")])),
                ('type', models.IntegerField(choices=[(0, 'Standard'), (1, 'Deluxe'), (2, 'Suit')])),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='rooms', to='app.amenity')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('book_until', models.DateTimeField()),
                ('paid_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.room')),
            ],
        ),
    ]
