# Generated by Django 5.2 on 2025-05-13 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.IntegerField(choices=[('ST', 'Standard'), ('DL', 'Deluxe'), ('SU', 'Suit')]),
        ),
    ]
