# Generated by Django 5.2 on 2025-04-16 09:15

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_image_thumbnail_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='default.png', force_format='JPEG', keep_meta=True, null=True, quality=90, scale=0.5, size=[200, 200], upload_to='profile_images'),
        ),
    ]
