# Generated by Django 5.2 on 2025-05-13 06:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_room_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booked_at',
            new_name='date_bookat',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='book_until',
            new_name='date_bookuntil',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='check_in',
            new_name='date_checkin',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='check_out',
            new_name='date_checkout',
        ),
        migrations.AddField(
            model_name='amenity',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amenity',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='room',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('ST', 'Standard'), ('DL', 'Deluxe'), ('SU', 'Suit')]),
        ),
    ]
