# Generated by Django 5.2 on 2025-05-14 10:45

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_booked_at_booking_date_bookat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Reservation',
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_.\\)\\(\\[\\]\\\\\\|\\s]+$', message="Allowed characters: a-z, A-Z, 0-9, '_', '.', '', '(', ')', '[', ']' and ' '.")]),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('ST', 'Standard'), ('DL', 'Deluxe'), ('SU', 'Suite')]),
        ),
    ]
