# Generated by Django 5.2 on 2025-05-14 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_booking_reservation_alter_room_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_bookfrom',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_bookat',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_bookuntil',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_checkin',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_checkout',
            field=models.DateField(blank=True),
        ),
    ]
