# Generated by Django 5.2 on 2025-04-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_roomimages_roomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='Room', max_length=100),
            preserve_default=False,
        ),
    ]
