# Generated by Django 5.2 on 2025-05-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_reservation_date_bookfrom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_checkin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_checkout',
            field=models.DateField(blank=True, null=True),
        ),
    ]
