# Generated by Django 5.2 on 2025-04-18 13:24

import app.utils
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_room_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='default.png', force_format='JPEG', keep_meta=True, null=True, quality=90, scale=0.5, size=[1920, 1080], upload_to=app.utils.room_upload_path),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='app.room'),
        ),
    ]
