# Generated by Django 5.2 on 2025-05-15 06:31

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_reservation_date_checkin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_bookfrom',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 5, 15, 14, 31, 48, 260292))]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_bookuntil',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 5, 15, 14, 31, 48, 260351))]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='app.room'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
    ]
