# Generated by Django 5.2 on 2025-04-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_amenity_options_alter_roomimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(default='Lorem ipsum'),
            preserve_default=False,
        ),
    ]
