# Generated by Django 5.2 on 2025-05-16 15:45

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_reservation_date_bookfrom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_bookfrom',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 5, 16))]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_bookuntil',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 5, 16))]),
        ),
    ]
