# Generated by Django 5.2 on 2025-05-17 00:56

import datetime
import django.core.validators
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_reservation_date_bookfrom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='default.png', force_format='JPEG', keep_meta=True, null=True, quality=90, scale=0.5, size=[200, 200], upload_to='images/profiles'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_bookfrom',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 5, 17))]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_bookuntil',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 5, 17))]),
        ),
    ]
