# Generated by Django 5.2 on 2025-05-17 01:40

import django.core.validators
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_profile_image_alter_reservation_date_bookfrom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_available',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='default.png', force_format='JPEG', keep_meta=True, null=True, quality=90, scale=0.5, size=[200, 200], upload_to='images/profiles', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'jfif', 'PNG', 'JPG'])]),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
