# Generated by Django 5.2 on 2025-05-17 01:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_reservation_discount_remove_room_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_.\\s-]{2,}$', message='Allowed characters: letters, numbers, and these " _.-".')]),
        ),
    ]
