# Generated by Django 5.2 on 2025-05-11 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_room_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_.\\)\\(\\[\\]\\\\\\|\\s]{4,}$', message="Allowed characters: a-z, A-Z, 0-9, '_', '.', '', '(', ')', '[', ']' and ' '.")]),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_.\\)\\(\\[\\]\\\\\\|\\s]{4,}$', message="Allowed characters: a-z, A-Z, 0-9, '_', '.', '', '(', ')', '[', ']' and ' '.")]),
        ),
    ]
