# Generated by Django 5.2 on 2025-05-11 14:16

import app.utils
import django.core.validators
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_room_description_alter_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='default.png', force_format='JPEG', keep_meta=True, null=True, quality=90, scale=0.5, size=[1920, 1080], upload_to=app.utils.room_upload_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'jfif', 'PNG', 'JPG'])]),
        ),
        migrations.DeleteModel(
            name='RoomImage',
        ),
    ]
