# Generated by Django 5.2 on 2025-05-11 14:22

import django.core.validators
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_room_image_delete_roomimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='default.png', force_format='JPEG', keep_meta=True, null=True, quality=90, scale=0.5, size=[1920, 1080], upload_to='images/rooms/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'jfif', 'PNG', 'JPG'])]),
        ),
    ]
