# Generated by Django 5.2 on 2025-05-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
